### ISSUE TITLE
Will there be any improvements?

### ISSUE THREAD

**Issue by Narayanna** [Nenkai/TCMotorfest.Unpacker#1]
Hello, my friend. I wonder if you will update the tool to import and export. Will it be possible to localize this game? We would really appreciate it if you could work on this.

**Comment by Nenkai** [comment]
This is an unpacker so exporting is already supported (provided you somehow have the means to get the remaining components to use this tool).
Importing is not planned, especially not during the game's supported period.

**Comment by Narayanna** [comment]
I understand, I hope there will be a development on this issue soon. Thanks.
